Controllers/PagesController.cs
using Forum.Models;
using Forum.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Forum.Controllers
{
    public class PagesController : Controller
    {
        private readonly UserManager<User> _userManager;
        private ForumContext _context;
        public PagesController(UserManager<User> userManager, ForumContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        public IActionResult Index()
        {
            IQueryable<Theme> themes = _context.Themes.Include(t => t.Creator);
            themes = themes.OrderByDescending(t => t.CreationDate);
            return View(themes.ToList());
        }
        [HttpGet]
        public IActionResult CreateTheme()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateTheme(Theme theme)
        {
            var user = _context.Users.Include(u => u.ProfilePic).FirstOrDefault(u => u.Id == _userManager.GetUserId(User));
            theme.CreatorId = user.Id;
            theme.Creator = user;
            theme.CreationDate = DateTime.Now;
            _context.Themes.Add(theme);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Details(int id)
        {
            var theme = _context.Themes.Include(t => t.Creator).FirstOrDefault(t => t.Id == id);
            var responses = _context.Responses.Include(r => r.User).Include(r => r.User.ProfilePic).Include(r => r.Theme).Where(r => r.ThemeId == id);
            responses = responses.OrderBy(r => r.CreationDate);
            DetailsViewModel dvm = new DetailsViewModel
            {
                Theme = theme,
                Responses = responses.ToList()
            };
            return View(dvm);
        }
        public IActionResult Search(string keyWord)
        {
            List<Theme> themes = _context.Themes.Include(p => p.Creator).Where(u =>
                u.Name.Contains(keyWord)).ToList();
            return View("Index", themes);
        }
        [HttpPost]
        public IActionResult CreateResponse(int themeId, string text)
        {
            var theme = _context.Themes.Include(t => t.Creator).FirstOrDefault(t => t.Id == themeId);
            var user = _context.Users.Include(u => u.ProfilePic).FirstOrDefault(u => u.Id == _userManager.GetUserId(User));
            Response response = new Response
            {
                UserId = user.Id,
                User = user,
                CreationDate = DateTime.Now,
                Text = text,
                ThemeId = theme.Id,
                Theme = theme
            };
            _context.Responses.Add(response);
            theme.ResponsesCount = theme.ResponsesCount + 1;
            _context.SaveChanges();
            var response2 = _context.Responses.Include(r => r.User).Include(r => r.User.ProfilePic).Include(r => r.Theme).FirstOrDefault(r => r.Text == text);
            return PartialView("PartialViews/ResponsePartialView", response2);
        }
        public IActionResult ResponseDisplay(string text)
        {
            var response = _context.Responses.Include(r => r.User).Include(r => r.User.ProfilePic).Include(r => r.Theme).FirstOrDefault(r => r.Text == text);
            return PartialView("PartialViews/ResponsePartialView", response);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Forum</title>
    <link rel="stylesheet" href="https://kit-free.fontawesome.com/releases/v5.11.1/css/free.min.css" media="all">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pages" asp-action="Index">Main page</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Pages" asp-action="CreateTheme">Create theme</a>
                            </li>
                            <li class="nav-item" style="margin-left: auto; margin-right: auto;">
                                <form id="search">
                                    <div class="form-outline">
                                        <input style="text-align: center;" type="text" id="SearchString" class="form-control" placeholder="Search"
                                               aria-label="Search" />
                                    </div>
                                </form>
                            </li>
                            <li class="nav-item" style="margin-left:auto;margin-top:auto;margin-bottom:auto;">
                                <form method="post" asp-controller="Account" asp-action="Logout">
                                    <input type="submit" value="Logout" class="nav-link text-light btn btn-secondary" />
                                </form>
                            </li>
                            <li>
                                <a class="nav-link text-dark btn btn-light" asp-area="" asp-controller="Account" asp-action="PersonalArea">Personal area</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item" style="margin-left: auto; margin-right: auto;">
                                <form id="search">
                                    <div class="form-outline">
                                        <input style="text-align: center;" type="text" id="SearchString" class="form-control" placeholder="Search"
                                               aria-label="Search" />
                                    </div>
                                </form>
                            </li>
                            <li>
                                <a class="nav-link text-light btn btn-secondary" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li>
                                <a class="nav-link text-dark btn btn-light" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Forum - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
   $('#search').on('submit', function (event) {
               event.preventDefault();
               var searchKey = $('#SearchString').val();
               searchKey = encodeURIComponent(searchKey);
               window.location.href = '@Url.Action("Search","Pages")?keyWord=' + searchKey;
           });
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>